source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target “Gank” do
    pod 'Kingfisher', '~> 2.4'
    pod 'Alamofire', '~> 3.4'
    pod "PKHUD"
    pod 'SKPhotoBrowser', '~> 1.8.6'
end
